name: Build and Publish to Development
on: workflow_dispatch
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Docker hub login
        run: docker login -p ${{ secret.DOCKER_USER }} -u ${{ secret.DOCKER_PASS }}
      - name: Build Container
        run: docker build -t sabnzbd:devel .
      - name: Tag container
        run: docker tag sabnzbd:devel ${{ secret.DOCKER_USER }}:development
      - name: Push container
        run: docker push ${{ secret.DOCKER_USER }}:development

