name: Build and Publish to Development
on: [push, workflow_dispatch]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Docker hub login
        run: docker login -p ${{ secrets.DOCKER_PASS }} -u ${{ secrets.DOCKER_USER }}
      - name: Build Container
        run: docker build -t sabnzbd:devel .
      - name: Tag container
        run: docker tag sabnzbd:devel "${{ secrets.DOCKER_USER }}/sabnzbd:development"
      - name: Push container
        run: docker push "${{ secrets.DOCKER_USER }}/sabnzbd:development"
      - name: Docker logout
        run: docker logout
